language: python
sudo: required

python:
  - "3.2"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - python setup.py install
  - sudo viki setup

script:
  - export PYTHONPATH=../
  - py.test test/
